### ISSUE TITLE
[11.0] Any keycard can open pedestals.

### ISSUE THREAD

**Issue by EsserGaming** [SebasCapo/RemoteKeycard#2]
No errors, just any keycard opens any pedestal.
Latest version of 11.0 remote keycard, latest public beta.

- Game version: 11.0.0-parabellum-rc-4-4689472e
- EXILED Version: 3.0.3
- Plugin version: 3.0

**Comment by ImBeryl** [comment]
Issue has been marked as fixed as of RK 3.1!
